apiVersion: batch/v1
kind: Job
metadata:
  name: cdkprocess
spec:
  template:
    metadata:
      name: cdkprocess-pod
    spec:
      containers:
      - name: cdkprocesses
        image: pavelstastny/cdkprocesses:1.0
        env:
          - name: URL1
            value: "https://www.seznam.cz"
          - name: URL2
            value: "https://www.seznam.cz"
        imagePullPolicy: Always
      restartPolicy: Never