openapi: 3.0.0
info:
  title: Metadata Response Schema
  version: 1.0.0

components:
  schemas:
    MetadataResponse:
      type: object
      description: >
        Odpověď pro metadata může být ve formátu Dublin Core (dc) nebo Biblio_MODS (mods).
        Struktura je určena externí dokumentací:
        - Dublin Core: [Dublin Core Documentation](https://example.com/dublin-core)
        - Biblio_MODS: [Biblio_MODS Documentation](https://example.com/biblio-mods)
      properties:
        metadataType:
          type: string
          enum:
            - dc
            - mods
          description: Typ metadat, určuje strukturu XML obsahu.
        content:
          type: string
          format: xml
          description: >
            XML obsah metadat. Struktura závisí na hodnotě `metadataType`.
            - Pro `dc`: struktura dle Dublin Core
            - Pro `mods`: struktura dle Biblio_MODS
      required:
        - metadataType
        - content
